version: "3.8"
services:
    wss:
        container_name: wss_php
        platform: linux/x86_64 # this works on for Mac m1 https://stackoverflow.com/a/69075554
        build:
            context: ./php
            dockerfile: Dockerfile
        image: wss_php
        working_dir: /var/www
        volumes:
            - ./src/www:/var/www
            - ./log:/var/log/wss
            - ./php/configs/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./php/configs/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        expose:
            - 9003
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - cex
    nginx:
        container_name: wss_nginx
        image: nginx
        depends_on:
            - wss
        volumes:
            - ./src/www:/var/www
            - ./log:/var/log/wss
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/ssl:/etc/nginx/ssl
        ports:
            - ${APP_HTTP_PORT}:80
            - ${APP_HTTPS_PORT}:443
        expose:
            - 81
        restart: always  
        networks:
            - cex

networks:
    cex:
        driver: bridge
        name: cex
        attachable: true
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  ip_range: 172.18.5.0/24
                  gateway: 172.18.0.1